:: IP Block
set hostspath=%windir%\System32\drivers\etc\hosts

echo 127.0.0.1 vortex.data.microsoft.com >> %hostspath%
echo 127.0.0.1 vortex-win.data.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 redir.metaservices.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 services.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.ppe.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net >> %hostspath%
echo 127.0.0.1 telemetry.urs.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net:443 >> %hostspath%
echo 127.0.0.1 vortex-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 settings-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 vortex.data.microsoft.com >> %hostspath%
echo 127.0.0.1 vortex-win.data.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 redir.metaservices.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 vortex-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 settings-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.ppe.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net >> %hostspath%
echo 127.0.0.1 telemetry.urs.microsoft.com >> %hostspath%
echo 127.0.0.1 survey.watson.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.live.com >> %hostspath%
echo 127.0.0.1 services.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net >> %hostspath%
echo 127.0.0.1 vortex.data.microsoft.com >> %hostspath%
echo 127.0.0.1 vortex-win.data.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 redir.metaservices.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com >> %hostspath%
echo 127.0.0.1 choice.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 services.wes.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 sqm.df.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.ppe.telemetry.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net >> %hostspath%
echo 127.0.0.1 telemetry.urs.microsoft.com >> %hostspath%
echo 127.0.0.1 telemetry.appex.bing.net:443 >> %hostspath%
echo 127.0.0.1 settings-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 vortex-sandbox.data.microsoft.com >> %hostspath%
echo 127.0.0.1 survey.watson.microsoft.com >> %hostspath%
echo 127.0.0.1 watson.live.com >> %hostspath%
echo 127.0.0.1 watson.microsoft.com >> %hostspath%
echo 127.0.0.1 statsfe2.ws.microsoft.com >> %hostspath%
echo 127.0.0.1 corpext.msitadfs.glbdns2.microsoft.com >> %hostspath%
echo 127.0.0.1 compatexchange.cloudapp.net >> %hostspath%
echo 127.0.0.1 cs1.wpc.v0cdn.net >> %hostspath%
echo 127.0.0.1 a-0001.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0002.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0003.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0004.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0005.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0006.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0007.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0008.a-msedge.net >> %hostspath%
echo 127.0.0.1 a-0009.a-msedge.net >> %hostspath%
echo 127.0.0.1 msedge.net >> %hostspath%
echo 127.0.0.1 a-msedge.net >> %hostspath%
echo 127.0.0.1 statsfe2.update.microsoft.com.akadns.net >> %hostspath%
echo 127.0.0.1 sls.update.microsoft.com.akadns.net >> %hostspath%
echo 127.0.0.1 fe2.update.microsoft.com.akadns.net >> %hostspath%
echo 127.0.0.1 diagnostics.support.microsoft.com >> %hostspath%
echo 127.0.0.1 corp.sts.microsoft.com >> %hostspath%
echo 127.0.0.1 statsfe1.ws.microsoft.com >> %hostspath%
echo 127.0.0.1 pre.footprintpredict.com >> %hostspath%
echo 127.0.0.1 i1.services.social.microsoft.com >> %hostspath%
echo 127.0.0.1 i1.services.social.microsoft.com.nsatc.net >> %hostspath%
echo 127.0.0.1 feedback.windows.com >> %hostspath%
echo 127.0.0.1 feedback.microsoft-hohm.com >> %hostspath%
echo 127.0.0.1 feedback.search.microsoft.com >> %hostspath%
echo 127.0.0.1 live.rads.msn.com >> %hostspath%
echo 127.0.0.1 ads1.msn.com >> %hostspath%
echo 127.0.0.1 static.2mdn.net >> %hostspath%
echo 127.0.0.1 g.msn.com >> %hostspath%
echo 127.0.0.1 a.ads2.msads.net >> %hostspath%
echo 127.0.0.1 b.ads2.msads.net >> %hostspath%
echo 127.0.0.1 ad.doubleclick.net >> %hostspath%
echo 127.0.0.1 ac3.msn.com >> %hostspath%
echo 127.0.0.1 rad.msn.com >> %hostspath%
echo 127.0.0.1 msntest.serving-sys.com >> %hostspath%
echo 127.0.0.1 bs.serving-sys.com1 >> %hostspath%
echo 127.0.0.1 flex.msn.com >> %hostspath%
echo 127.0.0.1 ec.atdmt.com >> %hostspath%
echo 127.0.0.1 cdn.atdmt.com >> %hostspath%
echo 127.0.0.1 db3aqu.atdmt.com >> %hostspath%
echo 127.0.0.1 cds26.ams9.msecn.net >> %hostspath%
echo 127.0.0.1 sO.2mdn.net >> %hostspath%
echo 127.0.0.1 aka-cdn-ns.adtech.de >> %hostspath%
echo 127.0.0.1 secure.flashtalking.com >> %hostspath%
echo 127.0.0.1 adnexus.net >> %hostspath%
echo 127.0.0.1 adnxs.com >> %hostspath%
echo 127.0.0.1 *.rad.msn.com >> %hostspath%
echo 127.0.0.1 *.msads.net >> %hostspath%
echo 127.0.0.1 *.msecn.net >> %hostspath%

del /f >NUL 2>&1 /Q "%WINDIR%\system32\drivers\etc\hosts" >NUL 2>&1
ECHO 0.0.0.0 telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex-win.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telecommand.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telecommand.telemetry.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 oca.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 oca.telemetry.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sqm.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sqm.telemetry.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 watson.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 watson.telemetry.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 redir.metaservices.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 choice.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 choice.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wes.df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 reports.wes.df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 services.wes.df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sqm.df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 watson.ppe.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.appex.bing.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.urs.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.appex.bing.net:443>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 settings-sandbox.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex-sandbox.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 watson.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 survey.watson.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 watson.live.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 statsfe2.ws.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 corpext.msitadfs.glbdns2.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 compatexchange.cloudapp.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cs1.wpc.v0cdn.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 a-0001.a-msedge.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 fe2.update.microsoft.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 statsfe2.update.microsoft.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sls.update.microsoft.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 diagnostics.support.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 corp.sts.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 statsfe1.ws.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pre.footprintpredict.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 i1.services.social.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 i1.services.social.microsoft.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 feedback.windows.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 feedback.microsoft-hohm.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 feedback.search.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.content.prod.cms.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.content.prod.cms.msn.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 e10663.g.akamaiedge.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dmd.metaservices.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 schemas.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 go.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.76.0.0/14>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.96.0.0/12>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.124.0.0/16>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.112.0.0/13>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.125.0.0/17>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.74.0.0/15>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.80.0.0/12>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 40.120.0.0/14>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 137.116.0.0/16>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 23.192.0.0/11>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 23.32.0.0/11>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 23.64.0.0/14>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 23.55.130.182>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 a.ads1.msads.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 a.ads1.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 a.ads2.msads.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 a.ads2.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.live.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bingads.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 browser.events.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cache.datamart.windows.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 events.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 manage.devcenter.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mobile.events.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mobile.pipe.aria.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 onecollector.cloudapp.aria.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 prod.nexusrules.live.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ris.api.iris.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 self.events.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 settings-win.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 spynet2.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 spynetalt.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telecommand.alpha.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telecommand.df.telemetry.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.appex.bing.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.urs.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetrysvc-by3p.smartscreen.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 us.vortex-win.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 v10-win.vortex.data.microsoft.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 v10.events.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 v10.vortex-win.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 v20.vortex-win.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex-bn2.metron.live.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex-cy2.metron.live.com.nsatc.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vortex.data.microsoft.com.akadns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 web.vortex.data.microsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.remoteapp.windowsazure.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.2mdn.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 b.ads1.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 b.ads2.msads.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 b.rad.msn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tele.trafficmanager.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1beb2a44.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1q2w3.fun>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1q2w3.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 300ca0d0.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 310ca263.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 320ca3f6.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 330ca589.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 340ca71c.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 360caa42.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 370cabd5.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 3c0cb3b4.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 3d0cb547.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 abc.pema.cl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad-miner.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.blue>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.inwemo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 azvjudwr.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 baiduccdn1.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 berserkpl.net.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 biberukalap.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bjorksta.men>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 blockchain.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 candid.zone>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.adless.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.cloudcoins.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 chainblock.science>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cnhv.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-have.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-hive.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinblind.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinerra.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinhive.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinhiveproxy.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinlab.biz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinnebula.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto-loot.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto-webminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto.csgocpu.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cryptoloot.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cryweb.github.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crywebber.github.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dev.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 digger.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flare-analytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 go.megabanners.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gridiogrid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gus.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hive.tubetitties.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hodlers.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hodling.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 host.d-ns.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 intactoffers.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jroqvbvw.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jsccnn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jscdndel.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jyhfuqoh.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kdowqlpt.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 load.jsecoin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 m.anyfiles.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mine.nahnoji.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mine.torrent.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minemytraffic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.nablabee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.pr0gramm.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-01.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-02.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-03.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 monerominer.rocks>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 noblock.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 okeyletsgo.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 papoto.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 playerassets.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ppoi.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 projectpoi.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 reservedoffers.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rocks.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 smectapop12.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sparnove.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.sparechange.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tokyodrift.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webassembly.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webmine.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webmine.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webminepool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webminepool.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wsp.marketgid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.cryptonoter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.mutuza.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.sparechange.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 xbasfbno.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cnhv.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-hive.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinhive.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 authedmine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.jsecoin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 load.jsecoin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 server.jsecoin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.pr0gramm.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minemytraffic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto-loot.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cryptaloot.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cryptoloot.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinerra.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-have.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-01.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-02.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minero-proxy-03.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.inwemo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rocks.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad-miner.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jsccnn.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jscdndel.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinhiveproxy.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinblind.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinnebula.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 monerominer.rocks>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.cloudcoins.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinlab.biz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 go.megabanners.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 baiduccdn1.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wsp.marketgid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 papoto.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flare-analytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.sparechange.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.sparechange.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.nablabee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 m.anyfiles.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.coinimp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.coinimp.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.racing>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.blockchained.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.cryptonoter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.mutuza.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto-webminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.adless.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hegrinhar.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 verresof.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hemnes.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tidafors.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 moneone.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 plexcoin.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.monkeyminer.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 go2.mercy.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinpirate.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 d.cpufan.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 krb.devphp.org.ua>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nfwebminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cfcdist.gdn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 node.cfcdist.gdn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webxmr.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 xmr.mining.best>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webminepool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webminepool.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hive.tubetitties.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 playerassets.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tokyodrift.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webassembly.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.webassembly.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 okeyletsgo.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 candid.zone>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webmine.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 andlache.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bablace.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bewaslac.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 biberukalap.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bowithow.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 butcalve.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 evengparme.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gridiogrid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hatcalter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kedtise.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ledinund.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nathetsof.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 renhertfo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rintindown.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sparnove.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 witthethim.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1q2w3.fun>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1q2w3.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bjorksta.men>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crypto.csgocpu.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 noblock.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 digger.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dev.cryptobara.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 reservedoffers.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mine.torrent.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 host.d-ns.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 abc.pema.cl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 js.nahnoji.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mine.nahnoji.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webmine.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.webmine.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 intactoffers.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.blue>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 smectapop12.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 berserkpl.net.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hodlers.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hodling.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 chainblock.science>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minescripts.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.minescripts.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.nablabee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wss.nablabee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 clickwith.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dronml.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 niematego.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tulip18.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 p.estream.to>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 didnkinrab.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ledhenone.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 losital.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mebablo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 moonsade.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nebabrop.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pearno.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rintinwa.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 willacrit.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www2.adfreetv.ch>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minr.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 new.minr.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 test.minr.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 staticsfs.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn-code.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 g-content.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.g-content.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.static-cnt.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cnt.statistic.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jquery-uim.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.jquery-uim.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn-jquery.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 p1.interestingz.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kippbeak.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pasoherb.gq>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 axoncoho.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 depttake.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flophous.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pr0gram.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 authedmine.eu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.monero-miner.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.datasecu.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jquery-cdn.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.etzbnfuigipwvs.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.terethat.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 freshrefresher.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.pzoifaum.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ws.pzoifaum.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.bhzejltg.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ws.bhzejltg.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 d.cfcnet.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vip.cfcnet.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 eu.cfcnet.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 as.cfcnet.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 us.cfcnet.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 eu.cfcdist.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 as.cfcdist.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 us.cfcdist.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gustaver.ddns.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 worker.salon.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.appelamule.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mepirtedic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.streambeam.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adzjzewsma.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ffinwwfpqi.gq>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ininmacerad.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mhiobjnirs.gq>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 open-hive-server-1.pp.ua>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pool.hws.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pool.etn.spacepools.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.aalbbh84.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.aymcsx.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros01.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros02.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros03.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros04.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros05.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros06.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros07.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros08.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros09.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros10.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros11.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aeros12.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 npcdn1.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mxcdn2.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sxcdn6.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mxcdn1.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sxcdn02.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sxcdn4.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jqcdn2.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sxcdn1.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sxcdn5.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wpcdn1.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jqcdn01.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jqcdn03.herokuapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 1q2w3.website>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 video.videos.vidto.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.play1.videos.vidto.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 playe.vidto.se>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 video.streaming.estream.to>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 eth-pocket.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 xvideosharing.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bestcoinsignals.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 eucsoft.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 traviilo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wasm24.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 xmr.cool>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.netflare.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdnjs.cloudflane.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.cloudflane.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 clgserv.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hide.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 graftpool.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 encoding.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 altavista.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 scaleway.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nexttime.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 never.ovh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 2giga.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webminerpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minercry.pt>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adplusplus.fr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ethtrader.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gobba.myeffect.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bauersagtnein.myeffect.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 besti.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jurty.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jurtym.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mfio.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mwor.gq>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 oei1.gq>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wordc.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 berateveng.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ctlrnwbv.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ermaseuc.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kdmkauchahynhrs.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 uoldid.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jqrcdn.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jqassets.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jqcdn.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jquerrycdn.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jqwww.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 lightminer.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.lightminer.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dl.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mlib.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minr.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ws.browsermine.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bmst.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bmnr.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bmcm.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bmcm.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 videoplayer2.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.video2.stream.vidzi.tv>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 001.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 002.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 003.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 004.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 005.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 006.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 007.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 008.0x1f4b0.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 authedwebmine.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.authedwebmine.cz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 skencituer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 site.flashx.cc>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play1.flashx.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play2.flashx.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play4.flashx.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play5.flashx.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 js.vidoza.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mm.zubovskaya-banya.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mysite.irkdsu.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.estream.nu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.estream.to>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.estream.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.play.estream.nu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.play.estream.to>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.play.estream.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.tainiesonline.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.vidzi.tv>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.pampopholf.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s3.pampopholf.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.malictuiar.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s3.malictuiar.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.play.tainiesonline.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ocean2.authcaptcha.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rock2.authcaptcha.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stone2.authcaptcha.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sass2.authcaptcha.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sea2.authcaptcha.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.flowplayer.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.pc.belicimo.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.power.tainiesonline.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.s01.vidtodo.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wm.yololike.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.mix.kinostuff.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.on.animeteatr.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.mine.gay-hotvideo.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.www.intellecthosting.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mytestminer.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.vb.wearesaudis.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flowplayer.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.flowplayer.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s3.flowplayer.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 thersprens.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.thersprens.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s3.thersprens.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gramombird.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.gramombird.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ugmfvqsu.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bsyauqwerd.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ccvwtdtwyu.trade>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 baywttgdhe.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pdheuryopd.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 iaheyftbsn.review>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 djfhwosjck.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 najsiejfnc.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zndaowjdnf.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 yqaywudifu.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 malictuiar.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proofly.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zminer.zaloapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vkcdnservice.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dexim.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 acbp0020171456.page.tl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vuryua.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minexmr.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gitgrub.pro>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 d8acddffe978b5dfcae6.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 eth-pocket.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 autologica.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 whysoserius.club>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aster18cdn.nl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nerohut.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gnrdomimplementation.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pon.ewtuyytdf45.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hhb123.tk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dzizsih.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nddmcconmqsy.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 silimbompom.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 unrummaged.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 fruitice.realnetwrk.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 synconnector.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 toftofcal.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gasolina.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 8jd2lfsq.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 afflow.18-plus.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 afminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aservices.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 becanium.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 brominer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn-analytics.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.static-cnt.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cloudcdn.gdn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-service.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinpot.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinrail.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 etacontent.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 exdynsrv.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 formulawire.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 go.bestmobiworld.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 goldoffer.online>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hallaert.online>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hashing.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 igrid.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 laserveradedomaina.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 machieved.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nametraff.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 offerreality.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ogrid.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 panelsave.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 party-vqgdyvoycc.now.sh>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pertholin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 premiumstats.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 serie-vostfr.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 salamaleyum.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 smartoffer.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stonecalcom.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 thewhizmarketing.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 thewhizproducts.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 thewise.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 traffic.tc-clicks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vcfs6ip5h6.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 web.dle-news.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webmining.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wp-monero-miner.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wtm.monitoringservice.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 xy.nullrefexcep.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 yrdrtzmsmt.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wss.rand.com.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.verifier.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.racing>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.review>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.science>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.trade>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jshosting.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.review>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.science>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.freecontent.trade>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.accountant>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.racing>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.review>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.science>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.trade>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.hostingcloud.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 minerad.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-cube.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-services.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 service4refresh.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 money-maker-script.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 money-maker-default.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 de-ner-mi-nis4.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 de-nis-ner-mi-5.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 de-mi-nis-ner2.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 de-mi-nis-ner.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mi-de-ner-nis3.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.soodatmish.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.thersprens.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.feesocrald.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn1.pebx.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.nexioniect.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.besstahete.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s2.myregeneaf.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s3.myregeneaf.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 reauthenticator.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rock.reauthenticator.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 serv1swork.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 str1kee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 f1tbit.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 g1thub.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 swiftmining.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cashbeet.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wmtech.website>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.notmining.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coinminingonline.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 alflying.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 alflying.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 alflying.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 anybest.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 anybest.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 anybest.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 anybest.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dubester.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dubester.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dubester.space>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightsy.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightsy.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightsy.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flighty.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightzy.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightzy.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flightzy.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gettate.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gettate.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gettate.racing>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mighbest.host>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mighbest.pw>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mighbest.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.bid>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.date>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.faith>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.party>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.stream>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 zymerget.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 statdynamic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 alpha.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.miner.beeppool.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beatingbytes.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 besocial.online>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beta.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bulls.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 de1.eu.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ethmedialab.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 feilding.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 foxton.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ganymed.beeppool.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 himatangi.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 levin.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mine.terorie.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-1.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-10.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-11.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-12.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-13.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-14.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-15.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-16.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-17.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-18.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-19.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-2.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-3.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-4.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-5.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-6.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-7.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-8.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-9.team.nimiq.agency>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-4.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-5.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-6.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-7.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner-deu-8.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.beeppool.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-deu-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-deu-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-deu-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-fra-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-fra-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mon-gbr-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nimiq.terorie.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nimiqtest.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ninaning.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 node.alpha.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 node.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nodeb.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 nodeone.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-can-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-deu-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-deu-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-fra-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-fra-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-fra-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-gbr-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-gbr-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-pol-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 proxy-pol-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 script.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-1.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-1.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-1.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-10.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-10.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-10.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-11.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-11.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-11.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-12.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-12.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-12.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-13.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-13.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-13.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-14.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-14.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-14.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-15.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-15.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-15.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-16.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-16.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-16.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-17.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-17.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-17.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-18.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-18.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-18.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-19.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-19.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-19.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-2.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-2.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-2.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-20.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-20.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-20.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-3.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-3.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-3.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-4.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-4.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-4.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-5.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-5.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-5.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-6.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-6.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-6.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-7.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-7.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-7.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-8.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-8.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-8.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-9.nimiq-network.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-9.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-9.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-can-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-can-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-deu-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-deu-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-deu-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-deu-4.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-4.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-5.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-fra-6.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-gbr-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-gbr-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-gbr-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-gbr-4.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-pol-1.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-pol-2.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-pol-3.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed-pol-4.inf.nimiq.network>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 seed1.sushipool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 shannon.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq1.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq2.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq3.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq4.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq5.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sunnimiq6.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tokomaru.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 whanganui.nimiqpool.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.besocial.online>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 miner.nimiq.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jscoinminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.jscoinminer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.tercabilis.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 play.istlandoll.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s01.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s02.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s03.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s04.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s05.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s06.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s07.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s08.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s09.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s10.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s100.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s11.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s12.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s13.hostcontent.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 binarybusiness.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bitcoin-pay.eu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cloud-miner.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cloud-miner.eu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 easyhash.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 srcip.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 srcips.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 4967133.fls.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 6498008.fls.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aax-us-east.amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 aax.amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad-apac.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad-emea.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad-g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.mo.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.pl.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.sg.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ad.uk.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adclick.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adman.gr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admarketing.yahoo.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admarvel.s3.amazonaws.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admedia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admicro1.vcmedia.vn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admicro2.vcmedia.vn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admitad.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admixer.co.kr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admixer.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admob.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 admulti.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adnxs.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adobesupportnumber.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adocean.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adonly.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adotsolution.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adotube.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adprotected.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adpublisher.s3.amazonaws.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adquota.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads-twitter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.ad2iction.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.admoda.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.aerserv.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.easy-ads.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.facebook.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.fotoable.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.glispa.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.linkedin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.marvel.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.matomymobile.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.mediaforge.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.midatlantic.aaa.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.mobilefuse.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.mobilityware.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.mobvertising.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.mopub.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.n-ws.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.ookla.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.pdbarea.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.pinger.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.pinterest.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.pubmatic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.reddit>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.reward.rakuten.jp>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.taptapnetworks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.tremorhub.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.xlxtra.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.yahoo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads.youtube.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ads2.contentabc.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsafeprotected.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsame.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adscale.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsee.jp>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.goforandroid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.kimia.es>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.mobillex.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.pandora.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.ubiyoo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adserver.unityads.unity3d.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservetx.media.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.co.uk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.ge>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adservice.google.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adshost2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsmo.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsmoloco.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsniper.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adspirit.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adspynet.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsrvmedia.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsrvr.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adsymptotic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adtaily.pl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adtech.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adtilt.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adtrack.king.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adultadworld.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adups.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adv.mxmcdn.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adversal.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adverticum.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 advertise.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 advertising.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 advertur.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 advombat.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adwhirl.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adwired.mobi>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adwods.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adx.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adz.mobi>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adzerk.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adzmedia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adzmobi.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 adzworld.in>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 affinity.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 affiz.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 agile-support.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 airpush.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 almancakurslari.gen.tr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 altitude-arena.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 am15.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazing-your-prize86.loan>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazoncareers.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazoncash.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazoncash.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonfromhome.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazongigs.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonhiring.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonmoney.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonprofits.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonprofits.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonrecruiter.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonwealth.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amazonwork.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amedi.cl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 americageekpayment.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 americageeks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amoad.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amobee.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 amptrack.dailymail.co.uk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.brave.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.facebook.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.ff.avast.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.libertymutual.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.modul.ac.at>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.pinterest.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.pointdrive.linkedin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.query.yahoo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.twitter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 analytics.yahoo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 andomedia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.appfireworks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.fusepowered.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.kiip.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.leadbolt.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 api.usebutton.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 app-measurement.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 app-trackings.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 app.adjust.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 app.link>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 appads.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 appclick.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 appleforsystem.ga>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 appmetrica.yandex.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 appscase.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 banners.klm.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 basecrew.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacon.clickequations.net.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacon.eb-collector.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons.gcp.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons2.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons3.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons4.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 beacons5.gvt2.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 becoquin.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bid.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 biokamakozmetik.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 bloggingfornetworking.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 branch.io>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 brotherprintersupportphonenumber.co.uk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 c.aaxads.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 c.amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdex.mu>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdn.doublesclick.me>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cdnjs.cloudflare.com.cdn.cloudflare.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cesid.com.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 check-testingyourprize16.live>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 chiropractic-wellness.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 classyleague.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 clickandflirt.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 client-event-reporter.twitch.tv>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cm.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 coin-hive.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 combee84.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 countess.twitch.tv>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crash.discordapp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 crash.steampowered.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 cum.fr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 d2v02itv0y9u9t.cloudfront.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 d355fqgqddpk8.cloudfront.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 digitechinfosolutions.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 download4.co>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 driverupdate.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 dunmebach.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 easyads.bg>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 easydownloadnow.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 economylube.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 errorconnect.webcam>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 euyexxwe.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 events.gfe.nvidia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 events.redditmedia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 fasterpropertybuyers.co.uk>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 fastframe.com.br>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 fgsmjjpn.top>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 firebaselogging.googleapis.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 flirt.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 forchaklaws.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 format557-info.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 freshmarketer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 geniegamer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ghochv3eng.trafficmanager.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gmil.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 google-analytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 googleads.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 googleads4.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 googleanalytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 googlesyndication.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 googletagmanager.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 goretail.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 gstaticadssl.l.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 harvestbiblefellowship.us>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 heshimed.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hostedocsp.globalsign.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 hotmailcustomersupport.com.au>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 i-mobile.co.jp>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 i-vengo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 i.skimresources.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ia-tracker.fbsbx.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 iad.appboy.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 iadsdk.apple.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 iamediaserve.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 imasdk.googleapis.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 improving.duckduckgo.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 incoming.telemetry.mozilla.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 infolinks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inmobi.cn>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inmobi.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inmobi.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inmobicdn.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inmobisdk-a.akamaihd.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inner-active.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 inner-active.mobi>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 innity.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 innovid.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 insightexpressai.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 integral-marketing.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 intellitxt.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 intermarkets.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 internetcareer.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 itshurley.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 jnhosting.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kallohonka.fi>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kipos.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 kurankitabevi.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 laze35.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 lb.usemaxserver.de>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 log.byteoversea.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 log.pinterest.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 logfiles.zoom.us>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 lord16.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mads.amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mail-ads.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 malengotours.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 matjournal.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.advisorchannel.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.asos.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.att.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.cvshealth.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.dynad.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 metrics.fedex.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 muonpreux.review>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 myphonesupport.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 mytilene.fr>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 myway.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 n4403ad.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 notify.bugsnag.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 onatonline.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 oneclicksupport.info>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 onlinetechsoft.weebly.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 p4-fbm4tfy4du3vk-rsg77dtzm53vwr6k-854535-i1-v6exp3.v4.metric.gstatic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 p4-fbm4tfy4du3vk-rsg77dtzm53vwr6ks-854535-i2-v6exp3.ds.metric.gstatic.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 page-confrim-safe.ml>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagead.googlesyndication.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagead.l.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagead1.googlesyndication.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagead2.googlesyndication.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagead46.l.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pagefair.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 partner.googleadservices.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 partner.intentmedia.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 partnerad.l.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 partnerearning.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 passporttraveleg.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pcoptimizerpro.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 perf-events.cloud.unity3d.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pflexads.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 phluant.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pixel.ad>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pixel.admobclick.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pixel.facebook.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 platinumphonesupport.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ponmile.myjino.ru>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 pubads.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 public.cloud.unity3d.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 reportcentral.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rereddit.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 retailpay.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 revsherri.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 rtb2.doubleverify.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 s.amazon-adsystem.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 saltofearthlightofworld.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 securepubads.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sessions.bugsnag.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 settings.crashlytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 slicktimesavers.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 smetrics.midatlantic.aaa.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 smmknight.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 spicychats.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 sporthome.cl>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ssl.google-analytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 st-n.ads1-adnow.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.ads-twitter.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 static.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stats.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stats.mediaforge.com.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stats.wp.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 stockretail.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 storejobs.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 strnet24.cf>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 survey.g.doubleclick.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tagmanager.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 telemetry.gfe.nvidia.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 theunknowncomposer.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 togethernetworks.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tom006.site>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tps20512.doubleverify.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 track.adform.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 track.cpatool.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 track.effiliation.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 track.wattpad.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 track.zappos.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.admarketplace.net.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.bp01.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.epicgames.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.feedmob.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.feedperfect.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.intl.miui.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.klickthru.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.opencandy.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 tracking.opencandy.com.s3.amazonaws.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 trafficjunky.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 trafficsourceoftoplevelcontentsources.download>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 trovi.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 ulla.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 universalpapercupmachines.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 us04logfiles.zoom.us>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 usa-usage.ime.cootek.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 usa.cc>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 uyoutube.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 v6analytics.htmedia.in.edgekey.net>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 video-ad-stats.googlesyndication.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vietbacsecurity.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 vm5apis.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 wapsort.win>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webserve.xyz>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 webstorejobs.org>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www-google-analytics.l.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www-googletagmanager.l.google.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.google-analytics.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.googletagmanager.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 www.googletagservices.com>>%windir%\system32\drivers\etc\hosts
ECHO 0.0.0.0 youtube.cleverads.vn>>%windir%\system32\drivers\etc\hosts